# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: analytics/analytics.proto for package 'flipt.analytics'

require 'grpc'
require 'analytics/analytics_pb'

module Flipt
  module Analytics
    module AnalyticsService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'flipt.analytics.AnalyticsService'

        rpc :GetFlagEvaluationsCount, ::Flipt::Analytics::GetFlagEvaluationsCountRequest, ::Flipt::Analytics::GetFlagEvaluationsCountResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
