# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flipt.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flipt.proto", :syntax => :proto3) do
    add_message "flipt.EvaluationRequest" do
      optional :request_id, :string, 1
      optional :flag_key, :string, 2
      optional :entity_id, :string, 3
      map :context, :string, :string, 4
    end
    add_message "flipt.EvaluationResponse" do
      optional :request_id, :string, 1
      optional :entity_id, :string, 2
      map :request_context, :string, :string, 3
      optional :match, :bool, 4
      optional :flag_key, :string, 5
      optional :segment_key, :string, 6
      optional :timestamp, :message, 7, "google.protobuf.Timestamp"
      optional :value, :string, 8
      optional :request_duration_millis, :double, 9
    end
    add_message "flipt.Flag" do
      optional :key, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :enabled, :bool, 4
      optional :created_at, :message, 5, "google.protobuf.Timestamp"
      optional :updated_at, :message, 6, "google.protobuf.Timestamp"
      repeated :variants, :message, 7, "flipt.Variant"
    end
    add_message "flipt.FlagList" do
      repeated :flags, :message, 1, "flipt.Flag"
    end
    add_message "flipt.GetFlagRequest" do
      optional :key, :string, 1
    end
    add_message "flipt.ListFlagRequest" do
      optional :limit, :int32, 1
      optional :offset, :int32, 2
    end
    add_message "flipt.CreateFlagRequest" do
      optional :key, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :enabled, :bool, 4
    end
    add_message "flipt.UpdateFlagRequest" do
      optional :key, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :enabled, :bool, 4
    end
    add_message "flipt.DeleteFlagRequest" do
      optional :key, :string, 1
    end
    add_message "flipt.Variant" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
      optional :key, :string, 3
      optional :name, :string, 4
      optional :description, :string, 5
      optional :created_at, :message, 6, "google.protobuf.Timestamp"
      optional :updated_at, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "flipt.CreateVariantRequest" do
      optional :flag_key, :string, 1
      optional :key, :string, 2
      optional :name, :string, 3
      optional :description, :string, 4
    end
    add_message "flipt.UpdateVariantRequest" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
      optional :key, :string, 3
      optional :name, :string, 4
      optional :description, :string, 5
    end
    add_message "flipt.DeleteVariantRequest" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
    end
    add_message "flipt.Segment" do
      optional :key, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :updated_at, :message, 5, "google.protobuf.Timestamp"
      repeated :constraints, :message, 6, "flipt.Constraint"
      optional :match_type, :enum, 7, "flipt.MatchType"
    end
    add_message "flipt.SegmentList" do
      repeated :segments, :message, 1, "flipt.Segment"
    end
    add_message "flipt.GetSegmentRequest" do
      optional :key, :string, 1
    end
    add_message "flipt.ListSegmentRequest" do
      optional :limit, :int32, 1
      optional :offset, :int32, 2
    end
    add_message "flipt.CreateSegmentRequest" do
      optional :key, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :match_type, :enum, 4, "flipt.MatchType"
    end
    add_message "flipt.UpdateSegmentRequest" do
      optional :key, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :match_type, :enum, 4, "flipt.MatchType"
    end
    add_message "flipt.DeleteSegmentRequest" do
      optional :key, :string, 1
    end
    add_message "flipt.Constraint" do
      optional :id, :string, 1
      optional :segment_key, :string, 2
      optional :type, :enum, 3, "flipt.ComparisonType"
      optional :property, :string, 4
      optional :operator, :string, 5
      optional :value, :string, 6
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :updated_at, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "flipt.CreateConstraintRequest" do
      optional :segment_key, :string, 1
      optional :type, :enum, 2, "flipt.ComparisonType"
      optional :property, :string, 3
      optional :operator, :string, 4
      optional :value, :string, 5
    end
    add_message "flipt.UpdateConstraintRequest" do
      optional :id, :string, 1
      optional :segment_key, :string, 2
      optional :type, :enum, 3, "flipt.ComparisonType"
      optional :property, :string, 4
      optional :operator, :string, 5
      optional :value, :string, 6
    end
    add_message "flipt.DeleteConstraintRequest" do
      optional :id, :string, 1
      optional :segment_key, :string, 2
    end
    add_message "flipt.Rule" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
      optional :segment_key, :string, 3
      repeated :distributions, :message, 4, "flipt.Distribution"
      optional :rank, :int32, 5
      optional :created_at, :message, 6, "google.protobuf.Timestamp"
      optional :updated_at, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "flipt.RuleList" do
      repeated :rules, :message, 1, "flipt.Rule"
    end
    add_message "flipt.ListRuleRequest" do
      optional :limit, :int32, 1
      optional :offset, :int32, 2
      optional :flag_key, :string, 3
    end
    add_message "flipt.GetRuleRequest" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
    end
    add_message "flipt.CreateRuleRequest" do
      optional :flag_key, :string, 1
      optional :segment_key, :string, 2
      optional :rank, :int32, 3
    end
    add_message "flipt.UpdateRuleRequest" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
      optional :segment_key, :string, 3
    end
    add_message "flipt.DeleteRuleRequest" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
    end
    add_message "flipt.OrderRulesRequest" do
      optional :flag_key, :string, 1
      repeated :rule_ids, :string, 2
    end
    add_message "flipt.Distribution" do
      optional :id, :string, 1
      optional :rule_id, :string, 2
      optional :variant_id, :string, 3
      optional :rollout, :float, 4
      optional :created_at, :message, 5, "google.protobuf.Timestamp"
      optional :updated_at, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "flipt.CreateDistributionRequest" do
      optional :flag_key, :string, 1
      optional :rule_id, :string, 2
      optional :variant_id, :string, 3
      optional :rollout, :float, 4
    end
    add_message "flipt.UpdateDistributionRequest" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
      optional :rule_id, :string, 3
      optional :variant_id, :string, 4
      optional :rollout, :float, 5
    end
    add_message "flipt.DeleteDistributionRequest" do
      optional :id, :string, 1
      optional :flag_key, :string, 2
      optional :rule_id, :string, 3
      optional :variant_id, :string, 4
    end
    add_enum "flipt.MatchType" do
      value :ALL_MATCH_TYPE, 0
      value :ANY_MATCH_TYPE, 1
    end
    add_enum "flipt.ComparisonType" do
      value :UNKNOWN_COMPARISON_TYPE, 0
      value :STRING_COMPARISON_TYPE, 1
      value :NUMBER_COMPARISON_TYPE, 2
      value :BOOLEAN_COMPARISON_TYPE, 3
    end
  end
end

module Flipt
  EvaluationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.EvaluationRequest").msgclass
  EvaluationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.EvaluationResponse").msgclass
  Flag = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.Flag").msgclass
  FlagList = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.FlagList").msgclass
  GetFlagRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.GetFlagRequest").msgclass
  ListFlagRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.ListFlagRequest").msgclass
  CreateFlagRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.CreateFlagRequest").msgclass
  UpdateFlagRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.UpdateFlagRequest").msgclass
  DeleteFlagRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.DeleteFlagRequest").msgclass
  Variant = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.Variant").msgclass
  CreateVariantRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.CreateVariantRequest").msgclass
  UpdateVariantRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.UpdateVariantRequest").msgclass
  DeleteVariantRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.DeleteVariantRequest").msgclass
  Segment = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.Segment").msgclass
  SegmentList = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.SegmentList").msgclass
  GetSegmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.GetSegmentRequest").msgclass
  ListSegmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.ListSegmentRequest").msgclass
  CreateSegmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.CreateSegmentRequest").msgclass
  UpdateSegmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.UpdateSegmentRequest").msgclass
  DeleteSegmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.DeleteSegmentRequest").msgclass
  Constraint = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.Constraint").msgclass
  CreateConstraintRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.CreateConstraintRequest").msgclass
  UpdateConstraintRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.UpdateConstraintRequest").msgclass
  DeleteConstraintRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.DeleteConstraintRequest").msgclass
  Rule = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.Rule").msgclass
  RuleList = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.RuleList").msgclass
  ListRuleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.ListRuleRequest").msgclass
  GetRuleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.GetRuleRequest").msgclass
  CreateRuleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.CreateRuleRequest").msgclass
  UpdateRuleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.UpdateRuleRequest").msgclass
  DeleteRuleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.DeleteRuleRequest").msgclass
  OrderRulesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.OrderRulesRequest").msgclass
  Distribution = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.Distribution").msgclass
  CreateDistributionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.CreateDistributionRequest").msgclass
  UpdateDistributionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.UpdateDistributionRequest").msgclass
  DeleteDistributionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.DeleteDistributionRequest").msgclass
  MatchType = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.MatchType").enummodule
  ComparisonType = Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.ComparisonType").enummodule
end
