# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: flipt.proto for package 'flipt'

require 'grpc'
require 'flipt_pb'

module Flipt
  module Flipt
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'flipt.Flipt'

      rpc :Evaluate, ::Flipt::EvaluationRequest, ::Flipt::EvaluationResponse
      rpc :BatchEvaluate, ::Flipt::BatchEvaluationRequest, ::Flipt::BatchEvaluationResponse
      rpc :GetNamespace, ::Flipt::GetNamespaceRequest, ::Flipt::Namespace
      rpc :ListNamespaces, ::Flipt::ListNamespaceRequest, ::Flipt::NamespaceList
      rpc :CreateNamespace, ::Flipt::CreateNamespaceRequest, ::Flipt::Namespace
      rpc :UpdateNamespace, ::Flipt::UpdateNamespaceRequest, ::Flipt::Namespace
      rpc :DeleteNamespace, ::Flipt::DeleteNamespaceRequest, ::Google::Protobuf::Empty
      rpc :GetFlag, ::Flipt::GetFlagRequest, ::Flipt::Flag
      rpc :ListFlags, ::Flipt::ListFlagRequest, ::Flipt::FlagList
      rpc :CreateFlag, ::Flipt::CreateFlagRequest, ::Flipt::Flag
      rpc :UpdateFlag, ::Flipt::UpdateFlagRequest, ::Flipt::Flag
      rpc :DeleteFlag, ::Flipt::DeleteFlagRequest, ::Google::Protobuf::Empty
      rpc :CreateVariant, ::Flipt::CreateVariantRequest, ::Flipt::Variant
      rpc :UpdateVariant, ::Flipt::UpdateVariantRequest, ::Flipt::Variant
      rpc :DeleteVariant, ::Flipt::DeleteVariantRequest, ::Google::Protobuf::Empty
      rpc :GetRule, ::Flipt::GetRuleRequest, ::Flipt::Rule
      rpc :ListRules, ::Flipt::ListRuleRequest, ::Flipt::RuleList
      rpc :CreateRule, ::Flipt::CreateRuleRequest, ::Flipt::Rule
      rpc :UpdateRule, ::Flipt::UpdateRuleRequest, ::Flipt::Rule
      rpc :OrderRules, ::Flipt::OrderRulesRequest, ::Google::Protobuf::Empty
      rpc :DeleteRule, ::Flipt::DeleteRuleRequest, ::Google::Protobuf::Empty
      rpc :GetRollout, ::Flipt::GetRolloutRequest, ::Flipt::Rollout
      rpc :ListRollouts, ::Flipt::ListRolloutRequest, ::Flipt::RolloutList
      rpc :CreateRollout, ::Flipt::CreateRolloutRequest, ::Flipt::Rollout
      rpc :UpdateRollout, ::Flipt::UpdateRolloutRequest, ::Flipt::Rollout
      rpc :DeleteRollout, ::Flipt::DeleteRolloutRequest, ::Google::Protobuf::Empty
      rpc :OrderRollouts, ::Flipt::OrderRolloutsRequest, ::Google::Protobuf::Empty
      rpc :CreateDistribution, ::Flipt::CreateDistributionRequest, ::Flipt::Distribution
      rpc :UpdateDistribution, ::Flipt::UpdateDistributionRequest, ::Flipt::Distribution
      rpc :DeleteDistribution, ::Flipt::DeleteDistributionRequest, ::Google::Protobuf::Empty
      rpc :GetSegment, ::Flipt::GetSegmentRequest, ::Flipt::Segment
      rpc :ListSegments, ::Flipt::ListSegmentRequest, ::Flipt::SegmentList
      rpc :CreateSegment, ::Flipt::CreateSegmentRequest, ::Flipt::Segment
      rpc :UpdateSegment, ::Flipt::UpdateSegmentRequest, ::Flipt::Segment
      rpc :DeleteSegment, ::Flipt::DeleteSegmentRequest, ::Google::Protobuf::Empty
      rpc :CreateConstraint, ::Flipt::CreateConstraintRequest, ::Flipt::Constraint
      rpc :UpdateConstraint, ::Flipt::UpdateConstraintRequest, ::Flipt::Constraint
      rpc :DeleteConstraint, ::Flipt::DeleteConstraintRequest, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
