# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: flipt.proto for package 'flipt'

require 'grpc'
require 'flipt_pb'

module Flipt
  module Flipt
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'flipt.Flipt'

      rpc :Evaluate, EvaluationRequest, EvaluationResponse
      rpc :GetFlag, GetFlagRequest, Flag
      rpc :ListFlags, ListFlagRequest, FlagList
      rpc :CreateFlag, CreateFlagRequest, Flag
      rpc :UpdateFlag, UpdateFlagRequest, Flag
      rpc :DeleteFlag, DeleteFlagRequest, Google::Protobuf::Empty
      rpc :CreateVariant, CreateVariantRequest, Variant
      rpc :UpdateVariant, UpdateVariantRequest, Variant
      rpc :DeleteVariant, DeleteVariantRequest, Google::Protobuf::Empty
      rpc :GetRule, GetRuleRequest, Rule
      rpc :ListRules, ListRuleRequest, RuleList
      rpc :OrderRules, OrderRulesRequest, Google::Protobuf::Empty
      rpc :CreateRule, CreateRuleRequest, Rule
      rpc :UpdateRule, UpdateRuleRequest, Rule
      rpc :DeleteRule, DeleteRuleRequest, Google::Protobuf::Empty
      rpc :CreateDistribution, CreateDistributionRequest, Distribution
      rpc :UpdateDistribution, UpdateDistributionRequest, Distribution
      rpc :DeleteDistribution, DeleteDistributionRequest, Google::Protobuf::Empty
      rpc :GetSegment, GetSegmentRequest, Segment
      rpc :ListSegments, ListSegmentRequest, SegmentList
      rpc :CreateSegment, CreateSegmentRequest, Segment
      rpc :UpdateSegment, UpdateSegmentRequest, Segment
      rpc :DeleteSegment, DeleteSegmentRequest, Google::Protobuf::Empty
      rpc :CreateConstraint, CreateConstraintRequest, Constraint
      rpc :UpdateConstraint, UpdateConstraintRequest, Constraint
      rpc :DeleteConstraint, DeleteConstraintRequest, Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
