# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta/meta.proto

require 'google/protobuf'

require 'google/api/httpbody_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meta/meta.proto", :syntax => :proto3) do
  end
end

module Flipt
  module Meta
  end
end
