# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: meta/meta.proto for package 'flipt.meta'

require 'grpc'
require 'meta/meta_pb'

module Flipt
  module Meta
    module MetadataService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'flipt.meta.MetadataService'

        rpc :GetConfiguration, ::Google::Protobuf::Empty, ::Google::Api::HttpBody
        rpc :GetInfo, ::Google::Protobuf::Empty, ::Google::Api::HttpBody
      end

      Stub = Service.rpc_stub_class
    end
  end
end
