# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta/meta.proto

require 'google/protobuf'

require 'google/api/httpbody_pb'
require 'google/protobuf/empty_pb'


descriptor_data = "\n\x0fmeta/meta.proto\x12\nflipt.meta\x1a\x19google/api/httpbody.proto\x1a\x1bgoogle/protobuf/empty.proto2\x90\x01\n\x0fMetadataService\x12\x42\n\x10GetConfiguration\x12\x16.google.protobuf.Empty\x1a\x14.google.api.HttpBody\"\x00\x12\x39\n\x07GetInfo\x12\x16.google.protobuf.Empty\x1a\x14.google.api.HttpBody\"\x00\x42\"Z go.flipt.io/flipt/rpc/flipt/metab\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Flipt
  module Meta
  end
end
