# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-swagger/options/annotations.proto

require 'google/protobuf'

require 'protoc-gen-swagger/options/openapiv2_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protoc-gen-swagger/options/annotations.proto", :syntax => :proto3) do
  end
end

module Grpc
  module Gateway
    module ProtocGenSwagger
      module Options
      end
    end
  end
end
