# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/auth.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/struct_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("auth/auth.proto", :syntax => :proto3) do
    add_message "flipt.auth.MethodInfo" do
      optional :method, :enum, 1, "flipt.auth.Method", json_name: "method"
      optional :enabled, :bool, 2, json_name: "enabled"
      optional :session_compatible, :bool, 3, json_name: "sessionCompatible"
      optional :metadata, :message, 4, "google.protobuf.Struct", json_name: "metadata"
    end
    add_message "flipt.auth.ListAuthenticationMethodsResponse" do
      repeated :methods, :message, 1, "flipt.auth.MethodInfo", json_name: "methods"
    end
    add_message "flipt.auth.Authentication" do
      optional :id, :string, 1, json_name: "id"
      optional :method, :enum, 2, "flipt.auth.Method", json_name: "method"
      optional :expires_at, :message, 3, "google.protobuf.Timestamp", json_name: "expiresAt"
      optional :created_at, :message, 4, "google.protobuf.Timestamp", json_name: "createdAt"
      optional :updated_at, :message, 5, "google.protobuf.Timestamp", json_name: "updatedAt"
      map :metadata, :string, :string, 6
    end
    add_message "flipt.auth.GetAuthenticationRequest" do
      optional :id, :string, 1, json_name: "id"
    end
    add_message "flipt.auth.ListAuthenticationsRequest" do
      optional :method, :enum, 1, "flipt.auth.Method", json_name: "method"
      optional :limit, :int32, 2, json_name: "limit"
      optional :page_token, :string, 3, json_name: "pageToken"
    end
    add_message "flipt.auth.ListAuthenticationsResponse" do
      repeated :authentications, :message, 1, "flipt.auth.Authentication", json_name: "authentications"
      optional :next_page_token, :string, 2, json_name: "nextPageToken"
    end
    add_message "flipt.auth.DeleteAuthenticationRequest" do
      optional :id, :string, 1, json_name: "id"
    end
    add_message "flipt.auth.ExpireAuthenticationSelfRequest" do
      proto3_optional :expires_at, :message, 1, "google.protobuf.Timestamp", json_name: "expiresAt"
    end
    add_message "flipt.auth.CreateTokenRequest" do
      optional :name, :string, 1, json_name: "name"
      optional :description, :string, 2, json_name: "description"
      optional :expires_at, :message, 3, "google.protobuf.Timestamp", json_name: "expiresAt"
    end
    add_message "flipt.auth.CreateTokenResponse" do
      optional :client_token, :string, 1, json_name: "clientToken"
      optional :authentication, :message, 2, "flipt.auth.Authentication", json_name: "authentication"
    end
    add_message "flipt.auth.AuthorizeURLRequest" do
      optional :provider, :string, 1, json_name: "provider"
      optional :state, :string, 2, json_name: "state"
    end
    add_message "flipt.auth.AuthorizeURLResponse" do
      optional :authorize_url, :string, 1, json_name: "authorizeUrl"
    end
    add_message "flipt.auth.CallbackRequest" do
      optional :provider, :string, 1, json_name: "provider"
      optional :code, :string, 2, json_name: "code"
      optional :state, :string, 3, json_name: "state"
    end
    add_message "flipt.auth.CallbackResponse" do
      optional :client_token, :string, 1, json_name: "clientToken"
      optional :authentication, :message, 2, "flipt.auth.Authentication", json_name: "authentication"
    end
    add_message "flipt.auth.VerifyServiceAccountRequest" do
      optional :service_account_token, :string, 1, json_name: "serviceAccountToken"
    end
    add_message "flipt.auth.VerifyServiceAccountResponse" do
      optional :client_token, :string, 1, json_name: "clientToken"
      optional :authentication, :message, 2, "flipt.auth.Authentication", json_name: "authentication"
    end
    add_enum "flipt.auth.Method" do
      value :METHOD_NONE, 0
      value :METHOD_TOKEN, 1
      value :METHOD_OIDC, 2
      value :METHOD_KUBERNETES, 3
    end
  end
end

module Flipt
  module Auth
    MethodInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.MethodInfo").msgclass
    ListAuthenticationMethodsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.ListAuthenticationMethodsResponse").msgclass
    Authentication = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.Authentication").msgclass
    GetAuthenticationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.GetAuthenticationRequest").msgclass
    ListAuthenticationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.ListAuthenticationsRequest").msgclass
    ListAuthenticationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.ListAuthenticationsResponse").msgclass
    DeleteAuthenticationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.DeleteAuthenticationRequest").msgclass
    ExpireAuthenticationSelfRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.ExpireAuthenticationSelfRequest").msgclass
    CreateTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.CreateTokenRequest").msgclass
    CreateTokenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.CreateTokenResponse").msgclass
    AuthorizeURLRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.AuthorizeURLRequest").msgclass
    AuthorizeURLResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.AuthorizeURLResponse").msgclass
    CallbackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.CallbackRequest").msgclass
    CallbackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.CallbackResponse").msgclass
    VerifyServiceAccountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.VerifyServiceAccountRequest").msgclass
    VerifyServiceAccountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.VerifyServiceAccountResponse").msgclass
    Method = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flipt.auth.Method").enummodule
  end
end
